// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkYoq_iLHp-hUv4AFZc6maOtC6csuKxxM',
    appId: '1:1044361551958:web:4ec9e6195ec432c7385bf7',
    messagingSenderId: '1044361551958',
    projectId: 'apna-gullak-42221',
    authDomain: 'apna-gullak-42221.firebaseapp.com',
    storageBucket: 'apna-gullak-42221.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcnDnZ6QmIhS3ziAof_7PN4pdWhePyI-U',
    appId: '1:1044361551958:android:45b81a3d8eb2858a385bf7',
    messagingSenderId: '1044361551958',
    projectId: 'apna-gullak-42221',
    storageBucket: 'apna-gullak-42221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChnDJFfbjSBNqkfeFNwvLg4WzI1cOJZhk',
    appId: '1:1044361551958:ios:5751fc4472bd375b385bf7',
    messagingSenderId: '1044361551958',
    projectId: 'apna-gullak-42221',
    storageBucket: 'apna-gullak-42221.firebasestorage.app',
    iosBundleId: 'com.example.apnaGullak',
  );
}
